--
-- AI Efficiency Optimization - Phase 1
-- Date: 2025-11-04
-- Description: Split BUY/SELL recommendations, add user tiers, extend data retention
--
-- This migration is safe to run multiple times (uses IF NOT EXISTS)
--

-- ============================================================================
-- 1. Add tier columns to users table
-- ============================================================================

-- Check if tier column exists, add if not
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'users' AND column_name = 'tier'
  ) THEN
    ALTER TABLE public.users ADD COLUMN tier VARCHAR(20) DEFAULT 'free';
    RAISE NOTICE 'Added tier column to users table';
  ELSE
    RAISE NOTICE 'tier column already exists in users table';
  END IF;
END $$;

DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'users' AND column_name = 'tier_updated_at'
  ) THEN
    ALTER TABLE public.users ADD COLUMN tier_updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    RAISE NOTICE 'Added tier_updated_at column to users table';
  ELSE
    RAISE NOTICE 'tier_updated_at column already exists in users table';
  END IF;
END $$;

-- Add check constraint for tier values (safe to run multiple times)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'users_tier_check'
  ) THEN
    ALTER TABLE public.users 
    ADD CONSTRAINT users_tier_check 
    CHECK (tier IN ('free', 'premium'));
    RAISE NOTICE 'Added users_tier_check constraint';
  ELSE
    RAISE NOTICE 'users_tier_check constraint already exists';
  END IF;
END $$;

COMMENT ON COLUMN public.users.tier IS 'User subscription tier: free or premium';
COMMENT ON COLUMN public.users.tier_updated_at IS 'When the tier was last changed';

-- ============================================================================
-- 2. Create discovery_recommendations table (global BUY recommendations)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.discovery_recommendations (
  id SERIAL PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL,
  strategy VARCHAR(20) NOT NULL,
  coin_universe VARCHAR(20) NOT NULL,
  confidence NUMERIC(5,2) NOT NULL,
  entry_price NUMERIC(20,8),
  stop_loss NUMERIC(20,8),
  take_profit_1 NUMERIC(20,8),
  take_profit_2 NUMERIC(20,8),
  position_size NUMERIC(5,4),
  risk_level VARCHAR(10),
  reasoning JSONB,
  sources TEXT[],
  discovery_score NUMERIC(5,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() + INTERVAL '1 year',
  
  CONSTRAINT discovery_recommendations_strategy_check 
    CHECK (strategy IN ('conservative', 'moderate', 'aggressive')),
  CONSTRAINT discovery_recommendations_coin_universe_check 
    CHECK (coin_universe IN ('top10', 'top50', 'top100')),
  CONSTRAINT discovery_recommendations_risk_level_check 
    CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH'))
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_discovery_recs_strategy_universe 
  ON public.discovery_recommendations(strategy, coin_universe, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_discovery_recs_symbol 
  ON public.discovery_recommendations(symbol, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_discovery_recs_expires 
  ON public.discovery_recommendations(expires_at);

CREATE INDEX IF NOT EXISTS idx_discovery_recs_created 
  ON public.discovery_recommendations(created_at DESC);

COMMENT ON TABLE public.discovery_recommendations IS 'Global BUY recommendations generated by discovery system, not user-specific';
COMMENT ON COLUMN public.discovery_recommendations.strategy IS 'Discovery strategy used: conservative, moderate, or aggressive';
COMMENT ON COLUMN public.discovery_recommendations.coin_universe IS 'Coin universe scanned: top10, top50, or top100';
COMMENT ON COLUMN public.discovery_recommendations.discovery_score IS 'Original composite score (0-100) from discovery algorithm';

-- ============================================================================
-- 3. Create portfolio_recommendations table (user-specific SELL recommendations)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.portfolio_recommendations (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  symbol VARCHAR(20) NOT NULL,
  confidence NUMERIC(5,2) NOT NULL,
  current_price NUMERIC(20,8),
  entry_price NUMERIC(20,8),
  stop_loss NUMERIC(20,8),
  take_profit_1 NUMERIC(20,8),
  take_profit_2 NUMERIC(20,8),
  unrealized_pnl NUMERIC(20,8),
  percent_gain NUMERIC(10,2),
  sell_reason VARCHAR(50),
  risk_level VARCHAR(10),
  reasoning JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() + INTERVAL '1 year',
  
  CONSTRAINT portfolio_recommendations_sell_reason_check 
    CHECK (sell_reason IN ('profit_target', 'risk_management', 'momentum_loss', 'resistance')),
  CONSTRAINT portfolio_recommendations_risk_level_check 
    CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH'))
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_portfolio_recs_user_active 
  ON public.portfolio_recommendations(user_id, expires_at);

CREATE INDEX IF NOT EXISTS idx_portfolio_recs_user_symbol 
  ON public.portfolio_recommendations(user_id, symbol, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_portfolio_recs_created 
  ON public.portfolio_recommendations(created_at DESC);

COMMENT ON TABLE public.portfolio_recommendations IS 'User-specific SELL recommendations based on portfolio positions';
COMMENT ON COLUMN public.portfolio_recommendations.sell_reason IS 'Why this position should be considered for exit';
COMMENT ON COLUMN public.portfolio_recommendations.unrealized_pnl IS 'Current unrealized profit/loss on the position';
COMMENT ON COLUMN public.portfolio_recommendations.percent_gain IS 'Percentage gain/loss from entry price';

-- ============================================================================
-- 4. Create market_conditions_log table (for dashboard and analysis)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.market_conditions_log (
  id SERIAL PRIMARY KEY,
  volatility_level VARCHAR(20) NOT NULL,
  volume_change NUMERIC(10,2),
  price_movements NUMERIC(5,2),
  news_activity INTEGER,
  btc_dominance NUMERIC(5,2),
  market_regime VARCHAR(20),
  review_interval_minutes INTEGER,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  CONSTRAINT market_conditions_volatility_check 
    CHECK (volatility_level IN ('low', 'medium', 'high', 'extreme')),
  CONSTRAINT market_conditions_regime_check 
    CHECK (market_regime IN ('bull', 'bear', 'sideways', 'volatile'))
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_market_conditions_created 
  ON public.market_conditions_log(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_market_conditions_volatility 
  ON public.market_conditions_log(volatility_level, created_at DESC);

COMMENT ON TABLE public.market_conditions_log IS 'Historical log of market conditions for analysis and dashboard display';
COMMENT ON COLUMN public.market_conditions_log.review_interval_minutes IS 'Calculated interval for next AI review based on conditions';

-- ============================================================================
-- 5. Update existing recommendations table expiry (if needed)
-- ============================================================================

-- Update default for future records
DO $$
BEGIN
  ALTER TABLE public.recommendations 
  ALTER COLUMN expires_at SET DEFAULT NOW() + INTERVAL '1 year';
  RAISE NOTICE 'Updated recommendations.expires_at default to 1 year';
EXCEPTION
  WHEN OTHERS THEN
    RAISE NOTICE 'Could not update recommendations.expires_at default (table may not exist yet)';
END $$;

COMMENT ON COLUMN public.recommendations.expires_at IS 'Expiry date (1 year retention for training/analysis)';

-- ============================================================================
-- Migration Complete
-- ============================================================================

DO $$
BEGIN
  RAISE NOTICE '✅ AI Efficiency Optimization - Phase 1 migration completed successfully';
  RAISE NOTICE 'Created tables: discovery_recommendations, portfolio_recommendations, market_conditions_log';
  RAISE NOTICE 'Added tier columns to users table';
  RAISE NOTICE 'Updated recommendations expiry to 1 year';
END $$;
